name: Run Python Code

on:
  workflow_dispatch:  # allows manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: python python/percentage.py
